name: Concurrent Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Download go-task
      uses: arduino/setup-task@v1
      run: |-
        task --version

    - name: Building
      run: |-
        mkdir -p bin
        ./build.sh

    - name: List binaries
      run: |-
        ls -la bin/